name: Update Predictions

on:
  # Allow manual triggering
  workflow_dispatch:

  # Schedule the workflow to run daily at a specific time (e.g., 12:00 UTC)
  schedule:
    - cron: "0 12 * * *"  # Adjust time as needed (UTC)

jobs:
  update-predictions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install transformers
           pip install torch
           pip install pandas
           pip install requests

    - name: Run the script
      run: python update_predictions.py

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add all_time_predictions.json
        git commit -m "Update predictions"
        git push
